### PR TITLE
fix(multiSelect): fix no showing text, fix missing canDrawQusetion

### PR DESCRIPTION
**Pull request by stellarArg**
Fix missing Component. Fix MultiSelect no showing labe, on checbox, add peerDependices and dependecies

### CODE REVIEW

**Review by mdumrauf — COMMENTED** [review]
Don't do everything in a single commit

**Review by mdumrauf — CHANGES_REQUESTED** [review]
Delete `AddOnList` component

**Review by mdumrauf — COMMENTED** [review]
`ModalConfirm` is only used in AddOnList?

**Comment by stellarArg** [comment]
Done the Changes Requested,

**Pull request merged**
